spring:
  application:
    name: mirror-springcloud-zuul
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: mirror-springcloud-web-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: mirror-springcloud-web-admin-feign

