spring:
  application:
    name: mirror-springcloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/mirrormingzZ/mirror-springcloud-demo/
          search-paths: respo
          username:
          password:

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411
    
